export type Icon = 
  "wi-alien" |
  "wi-barometer" |
  "wi-celsius" |
  "wi-cloud-down" |
  "wi-cloud-refresh" |
  "wi-cloud-up" |
  "wi-cloud" |
  "wi-cloudy-gusts" |
  "wi-cloudy-windy" |
  "wi-cloudy" |
  "wi-day-cloudy-gusts" |
  "wi-day-cloudy-high" |
  "wi-day-cloudy-windy" |
  "wi-day-cloudy" |
  "wi-day-fog" |
  "wi-day-hail" |
  "wi-day-haze" |
  "wi-day-light-wind" |
  "wi-day-lightning" |
  "wi-day-rain-wind" |
  "wi-day-rain-mix" |
  "wi-day-rain" |
  "wi-day-showers" |
  "wi-day-sleet-storm" |
  "wi-day-sleet" |
  "wi-day-snow-thunderstorm" |
  "wi-day-snow-wind" |
  "wi-day-snow" |
  "wi-day-sprinkle" |
  "wi-day-storm-showers" |
  "wi-day-sunny-overcast" |
  "wi-day-sunny" |
  "wi-day-thunderstorm" |
  "wi-day-windy" |
  "wi-degrees" |
  "wi-direction-down-left" |
  "wi-direction-down-right" |
  "wi-direction-down" |
  "wi-direction-left" |
  "wi-direction-right" |
  "wi-direction-up-left" |
  "wi-direction-up-right" |
  "wi-direction-up" |
  "wi-dust" |
  "wi-earthquake" |
  "wi-fahrenheit" |
  "wi-fire" |
  "wi-flood" |
  "wi-fog" |
  "wi-gale-warning" |
  "wi-hail" |
  "wi-horizon-alt" |
  "wi-horizon" |
  "wi-hot" |
  "wi-humidity" |
  "wi-hurricane-warning" |
  "wi-hurricane" |
  "wi-lightning" |
  "wi-lunar-eclipse" |
  "wi-meteor" |
  "wi-moon-alt-first-quarter" |
  "wi-moon-alt-full" |
  "wi-moon-alt-new" |
  "wi-moon-alt-third-quarter" |
  "wi-moon-alt-waning-crescent-1" |
  "wi-moon-alt-waning-crescent-2" |
  "wi-moon-alt-waning-crescent-3" |
  "wi-moon-alt-waning-crescent-4" |
  "wi-moon-alt-waning-crescent-5" |
  "wi-moon-alt-waning-crescent-6" |
  "wi-moon-alt-waning-gibbous-1" |
  "wi-moon-alt-waning-gibbous-2" |
  "wi-moon-alt-waning-gibbous-3" |
  "wi-moon-alt-waning-gibbous-4" |
  "wi-moon-alt-waning-gibbous-5" |
  "wi-moon-alt-waning-gibbous-6" |
  "wi-moon-alt-waxing-crescent-1" |
  "wi-moon-alt-waxing-crescent-2" |
  "wi-moon-alt-waxing-crescent-3" |
  "wi-moon-alt-waxing-crescent-4" |
  "wi-moon-alt-waxing-crescent-5" |
  "wi-moon-alt-waxing-crescent-6" |
  "wi-moon-alt-waxing-gibbous-1" |
  "wi-moon-alt-waxing-gibbous-2" |
  "wi-moon-alt-waxing-gibbous-3" |
  "wi-moon-alt-waxing-gibbous-4" |
  "wi-moon-alt-waxing-gibbous-5" |
  "wi-moon-alt-waxing-gibbous-6" |
  "wi-moon-first-quarter" |
  "wi-moon-full" |
  "wi-moon-new" |
  "wi-moon-third-quarter" |
  "wi-moon-waning-crescent-1" |
  "wi-moon-waning-crescent-2" |
  "wi-moon-waning-crescent-3" |
  "wi-moon-waning-crescent-4" |
  "wi-moon-waning-crescent-5" |
  "wi-moon-waning-crescent-6" |
  "wi-moon-waning-gibbous-1" |
  "wi-moon-waning-gibbous-2" |
  "wi-moon-waning-gibbous-3" |
  "wi-moon-waning-gibbous-4" |
  "wi-moon-waning-gibbous-5" |
  "wi-moon-waning-gibbous-6" |
  "wi-moon-waxing-6" |
  "wi-moon-waxing-crescent-1" |
  "wi-moon-waxing-crescent-2" |
  "wi-moon-waxing-crescent-3" |
  "wi-moon-waxing-crescent-4" |
  "wi-moon-waxing-crescent-5" |
  "wi-moon-waxing-gibbous-1" |
  "wi-moon-waxing-gibbous-2" |
  "wi-moon-waxing-gibbous-3" |
  "wi-moon-waxing-gibbous-4" |
  "wi-moon-waxing-gibbous-5" |
  "wi-moon-waxing-gibbous-6" |
  "wi-moonrise" |
  "wi-moonset" |
  "wi-na" |
  "wi-night-alt-cloudy-gusts" |
  "wi-night-alt-cloudy-high" |
  "wi-night-alt-cloudy-windy" |
  "wi-night-alt-cloudy" |
  "wi-night-alt-hail" |
  "wi-night-alt-lightning" |
  "wi-night-alt-partly-cloudy" |
  "wi-night-alt-rain-mix" |
  "wi-night-alt-rain-wind" |
  "wi-night-alt-rain" |
  "wi-night-alt-showers" |
  "wi-night-alt-sleet-storm" |
  "wi-night-alt-sleet" |
  "wi-night-alt-snow-thunderstorm" |
  "wi-night-alt-snow-wind" |
  "wi-night-alt-snow" |
  "wi-night-alt-sprinkle" |
  "wi-night-alt-storm-showers" |
  "wi-night-alt-thunderstorm" |
  "wi-night-clear" |
  "wi-night-cloudy-gusts" |
  "wi-night-cloudy-high" |
  "wi-night-cloudy-windy" |
  "wi-night-cloudy" |
  "wi-night-fog" |
  "wi-night-hail" |
  "wi-night-lightning" |
  "wi-night-partly-cloudy" |
  "wi-night-rain-mix" |
  "wi-night-rain-wind" |
  "wi-night-rain" |
  "wi-night-showers" |
  "wi-night-sleet-storm" |
  "wi-night-sleet" |
  "wi-night-snow-thunderstorm" |
  "wi-night-snow-wind" |
  "wi-night-snow" |
  "wi-night-sprinkle" |
  "wi-night-storm-showers" |
  "wi-night-thunderstorm" |
  "wi-rain-mix" |
  "wi-rain-wind" |
  "wi-rain" |
  "wi-raindrop" |
  "wi-raindrops" |
  "wi-refresh-alt" |
  "wi-refresh" |
  "wi-sandstorm" |
  "wi-showers" |
  "wi-sleet" |
  "wi-small-craft-advisory" |
  "wi-smog" |
  "wi-smoke" |
  "wi-snow-wind" |
  "wi-snow" |
  "wi-snowflake-cold" |
  "wi-solar-eclipse" |
  "wi-sprinkle" |
  "wi-stars" |
  "wi-storm-showers" |
  "wi-storm-warning" |
  "wi-strong-wind" |
  "wi-sunrise" |
  "wi-sunset" |
  "wi-thermometer-exterior" |
  "wi-thermometer-internal" |
  "wi-thermometer" |
  "wi-thunderstorm" |
  "wi-time-1" |
  "wi-time-10" |
  "wi-time-11" |
  "wi-time-12" |
  "wi-time-2" |
  "wi-time-3" |
  "wi-time-4" |
  "wi-time-5" |
  "wi-time-6" |
  "wi-time-7" |
  "wi-time-8" |
  "wi-time-9" |
  "wi-tornado" |
  "wi-train" |
  "wi-tsunami" |
  "wi-umbrella" |
  "wi-volcano" |
  "wi-wind-beaufort-0" |
  "wi-wind-beaufort-1" |
  "wi-wind-beaufort-10" |
  "wi-wind-beaufort-11" |
  "wi-wind-beaufort-12" |
  "wi-wind-beaufort-2" |
  "wi-wind-beaufort-3" |
  "wi-wind-beaufort-4" |
  "wi-wind-beaufort-5" |
  "wi-wind-beaufort-6" |
  "wi-wind-beaufort-7" |
  "wi-wind-beaufort-8" |
  "wi-wind-beaufort-9" |
  "wi-wind-deg" |
  "wi-windy" 